version: "3.7"

services:
  employeesservice:
    build: .
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch_importer/elasticsearch_importer:7.11.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  es-net:
    driver: bridge
